-- RFID Tag Registry Table
CREATE TABLE IF NOT EXISTS rfid_tags (
  epc VARCHAR(100) PRIMARY KEY,
  sku VARCHAR(100) NOT NULL,
  serial_number VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  last_seen_at TIMESTAMP WITH TIME ZONE,
  last_location VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
